require("custom.settings.harpoon")
require("custom.settings.lint")
require("custom.settings.autotag")
require("custom.settings.tinymist")
require("custom.settings.align")
-- require("custom.settings.typst-preview")
